import Layout from "@/components/Layout";
import Head from "next/head";
import profilePic from "../../public/images/profile/myPic.png";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import Transition from "@/components/Transition";

export default function Home() {
  return (
    <>
      <Head>
        <title>{"kajal's Portfolio"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Transition />
      <main className="flex items-center text-dark w-full dark:text-light min-h-screen">
        <Layout className="pt-0 md:pt-16 sm:pt-8 xs:pt-0">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/4 ml-20 md:w-1/2 md:ml-0">
              <Image
                src={profilePic}
                alt="kk"
                className="w-full h-auto lg:hidden md:inline-block md:w-full md:mb-4 xs:mb-4"
                priority
                sizes="(max-width: 768px) 100vw, (max-width:1200px) 50vw, 33vw"
              />
            </div>
            <div className="w-3/4 ml-20 flex flex-col items-center self-center lg:w-full lg:text-center md:ml-0">
              <AnimatedText
                text="Code, Design, Create: Transforming Visions into Digital Experiences"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-4xl sm:!text-3xl xs:!text-2xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs xs:text-start">
                {
                  " Hi, I'm a front-end enthusiast on a mission to create captivating websites. Take a tour of my latest projects where I delve into the world of React.js and the art of creating engaging web."
                }
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="https://drive.google.com/file/d/1ru6s_wNPivP4WyIulmPpYK8g7dcRebxh/view?usp=drivesdk"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 
                  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark 
                  border-2 border-solid border-transparent hover:border-dark dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link
                  href="mailto:kajalkapadiya18@gmail.com"
                  target="_blank"
                  className="ml-4 text-lg font-medium capitalize dark:text-light text-dark underline md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
